# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    image.adapter:
      custom:
        service: creative_selectel.adapter.adapter
    video.adapter:
      custom:
        service: creative_selectel.adapter.adapter
  filesystems:
    image.filesystem:
      adapter: image.adapter
    video.filesystem:
      adapter: video.adapter
