# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    image.adapter:
      awss3v3:
        client: Aws\S3\S3ClientInterface
        bucket: '%env(SELECTEL_CONTAINER)%'
        prefix: ''
    video.adapter:
      awss3v3:
        client: Aws\S3\S3ClientInterface
        bucket: '%env(SELECTEL_CONTAINER)%'
        prefix: ''
  filesystems:
    image.filesystem:
      adapter: image.adapter
    video.filesystem:
      adapter: video.adapter
