# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    image.adapter:
      local:
        directory: '%kernel.cache_dir%/images'
    video.adapter:
      local:
        directory: '%kernel.cache_dir%/video'
  filesystems:
    image.filesystem:
      adapter: image.adapter
    video.filesystem:
      adapter: video.adapter
