monolog:
  handlers:
    info:
      type: fingers_crossed
      action_level: info
      handler: nested_info
      buffer_size: 50
    nested_info:
      type: stream
      path: "php://stdout"
      level: debug

    error:
      type: fingers_crossed
      action_level: error
      handler: nested_err
      excluded_http_codes: [404, 405]
      buffer_size: 50
    nested_err:
      type: stream
      path: "php://stderr"
      level: debug

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
