# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  images_url_prefix: '%env(IMAGES_URL_PREFIX)%'
  video_url_prefix: '%env(VIDEO_URL_PREFIX)%'
  security_header_secret: '%env(SECURITY_HEADER_SECRET)%'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Aws\S3\S3ClientInterface:
    class: Aws\S3\S3Client
    arguments:
      -
        version: 'latest'
        region: 'ru-1a'
        use_path_style_endpoint: true
        endpoint: '%env(SELECTEL_S3_ENDPOINT)%'
        credentials:
          key: '%env(SELECTEL_CLIENT_ID)%'
          secret: '%env(SELECTEL_CLIENT_PASSWORD)%'

  file_handler.image:
    class: App\Service\Handler\ImageHandler
    arguments:
      - '@oneup_flysystem.image.filesystem_filesystem'
    calls:
      - setUrlPrefix: ['%images_url_prefix%']
    tags: { name: 'file.handler' }

  file_handler.video:
    class: App\Service\Handler\VideoHandler
    arguments:
      - '@oneup_flysystem.video.filesystem_filesystem'
    calls:
      - setUrlPrefix: ['%video_url_prefix%']
    tags: { name: 'file.handler' }

  App\Service\FileReceiverInterface:
    class: App\Service\FileReceiver
    arguments:
      - ['@file_handler.video', '@file_handler.image']

  App\Service\StreamProvider:
    arguments:
      $adapters: { images: '@oneup_flysystem.image.adapter_adapter', video: '@oneup_flysystem.video.adapter_adapter' }
      $s3Client: '@Aws\S3\S3ClientInterface'
      $bucket: '%env(SELECTEL_CONTAINER)%'

  App\Controller\FileAccess\DeleteController:
    arguments:
      $filesystems: {images: '@oneup_flysystem.image.filesystem_filesystem', video: '@oneup_flysystem.video.filesystem_filesystem'}
    tags: ['controller.service_arguments']

  App\Controller\FileAccess\DownloadController:
    tags: ['controller.service_arguments']
    arguments:
      $filesystems: {images: '@oneup_flysystem.image.filesystem_filesystem', video: '@oneup_flysystem.video.filesystem_filesystem'}
