# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  file_handler.image:
    class: App\Service\Handler\ImageHandler
    arguments:
      - '@oneup_flysystem.image.filesystem_filesystem'
    tags: { name: 'file.handler' }

  file_handler.video:
    class: App\Service\Handler\VideoHandler
    arguments:
      - '@oneup_flysystem.video.filesystem_filesystem'
    tags: { name: 'file.handler' }

  App\Service\FileReceiverInterface:
    class: App\Service\FileReceiver
    arguments:
      - ['@file_handler.video', '@file_handler.image']

  App\Controller\DownloadController:
    arguments:
      - images: '@oneup_flysystem.image.filesystem_filesystem'
        video: '@oneup_flysystem.video.filesystem_filesystem'
